### PR TITLE
IconToggleButton

### PR DESCRIPTION
**Pull request by gatimus**

### CODE REVIEW

**Comment by JoanZapata** [comment]
Thanks @gatimus !

**Comment by gatimus** [comment]
np, I'm going to use it for a play/pause button, love this library.

**Comment by rodrigoAbril** [comment]
Hi guys can you explain how do i use this?

**Comment by gatimus** [comment]
<IconToggleButton
                        android:textOff="{fa-play}"
                        android:textOn="{fa-pause}"/>

**Comment by matthew-reilly** [comment]
This doesn't seem to work at all in V2 with the following XML. The icon is not rendered.

``` <com.joanzapata.iconify.widget.IconToggleButton
         
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
           
            android:textOff="{fa-play}"
            android:textColor="@color/font_white"
            android:textSize="@dimen/text_large"/>
```

**Pull request merged**
